version: "3.7"

services:
  item-app:
    image: ghcr.io/didoramadhan/item-app]
    ports:
      - 80:8080
    depends_on:
      - item-db
    restart: always

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db:
